Different tests

t test: sample size is small, up to 30 samples

z test: want to work with pop mean and SD, more samples

f test

chi square test: categorical values

In [1]:
# Importing the required libraries
from scipy.stats import ttest_1samp
import numpy as np

In [6]:
# Creating a sample of ages
ages = [45, 89, 23, 46, 12, 69, 45, 24, 34, 67]
print(ages)

# Calculating the mean of the sample
mean = np.mean(ages)
print(mean)

# Performing the T-Test
t_test, p_val = ttest_1samp(ages, 40)
print("P-value is: ", p_val)

# taking the threshold value as 0.05 or 5%
if p_val < 0.05:
    print(" We can reject the null hypothesis")
else:
    print("We can accept the null hypothesis")

[45, 89, 23, 46, 12, 69, 45, 24, 34, 67]
45.4
P-value is:  0.49260884858714715
We can accept the null hypothesis

perform t-test on 2 samples

2 data groups and compare their means

In [7]:
# Importing the required libraries
from scipy.stats import ttest_ind
import numpy as np

# Creating the data groups
data_group1 = np.array([12, 18, 12, 13, 15, 1, 7,
                        20, 21, 25, 19, 31, 21, 17,
                        17, 15, 19, 15, 12, 15])
data_group2 = np.array([23, 22, 24, 25, 21, 26, 21,
                        21, 25, 30, 24, 21, 23, 19,
                        14, 18, 14, 12, 19, 15])

# Calculating the mean of the two data groups
mean1 = np.mean(data_group1)
mean2 = np.mean(data_group2)

# Print mean values
print("Data group 1 mean value:", mean1)
print("Data group 2 mean value:", mean2)

# Calculating standard deviation
#std1 = np.std(data_group1)
#std2 = np.std(data_group2)

# Printing standard deviation values
#print("Data group 1 std value:", std1)
#print("Data group 2 std value:", std2)

# Implementing the t-test
t_test,p_val = ttest_ind(data_group1, data_group2)
print("The P-value is: ", p_val)

# taking the threshold value as 0.05 or 5%
if p_val < 0.05:
    print("We can reject the null hypothesis")
else:
    print("We can accept the null hypothesis")

Data group 1 mean value: 16.25
Data group 2 mean value: 20.85
The P-value is:  0.012117171124028792
We can reject the null hypothesis

# Z test

- z test data is normally distributed
- sample size is more than 30

z score

In [10]:
from statsmodels.stats.weightstats import ztest as ztest


#enter IQ levels for 20 patients
data = [88, 92, 94, 94, 96, 97, 97, 97, 99, 99,
        105, 109, 109, 109, 110, 112, 112, 113, 114, 115]

#perform one sample z-test
z_test,p_val=ztest(data, value=100)

# taking the threshold value as 0.05 or 5%
print(p_val)
if p_val < 0.05:
    print("We can reject the null hypothesis")
else:
    print("We can accept the null hypothesis")

0.1101266701438426
We can accept the null hypothesis

In [11]:
#enter IQ levels for 20 individuals from each city
cityA = [82, 84, 85, 89, 91, 91, 92, 94, 99, 99,
         105, 109, 109, 109, 110, 112, 112, 113, 114, 114]

cityB = [90, 91, 91, 91, 95, 95, 99, 99, 108, 109,
         109, 114, 115, 116, 117, 117, 128, 129, 130, 133]

#perform two sample z-test
z_test,p_val=ztest(cityA, cityB, value=0)

print("The P-value is: ", p_val)

# taking the threshold value as 0.05 or 5%
if p_val < 0.05:
    print("We can reject the null hypothesis")
else:
    print("We can accept the null hypothesis")

#null says both city have the same mean

The P-value is:  0.046007596761332065
We can reject the null hypothesis

t and z for 2 groups.\
For more than 2 datasets\
Analysis of variance ANOVA

In [12]:
# Python program to implement One-Way f-test

# Importing the required libraries
import scipy.stats

# Creating sample data
data1 = [0.0842, 0.0368, 0.0847, 0.0935, 0.0376, 0.0963, 0.0684,
             0.0758, 0.0854, 0.0855]
data2 = [0.0785, 0.0845, 0.0758, 0.0853, 0.0946, 0.0785, 0.0853,
           0.0685]
data3 = [0.0864, 0.2522, 0.0894, 0.2724, 0.0853, 0.1367, 0.853]

# Performing the F-Test
f_test, p_val = scipy.stats.f_oneway(data1, data2, data3)
print("p-value is: ", p_val)

# taking the threshold value as 0.05 or 5%
if p_val < 0.05:
    print(" We can reject the null hypothesis")
else:
    print("We can accept the null hypothesis")

p-value is:  0.04043792126789144
 We can reject the null hypothesis

# chi square test

with categorical data\
.........Satisfied   Disstis\
Male\
Female

In [13]:
import scipy.stats as stats
import numpy as np

# Create a contingency table
# Rows: Male, Female | Columns: Satisfied, Dissatisfied
observed = np.array([[45, 15], [30, 25]])

# Perform chi-square test
chi2_stat, p_value, dof, expected = stats.chi2_contingency(observed)

# Check if the result is significant
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant association between gender and job satisfaction.")
else:
    print("Fail to reject the null hypothesis: There is no significant association between gender and job satisfaction.")

# Print chi-square statistic, p-value, degrees of freedom, and expected frequencies
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies:\n{expected}")

Reject the null hypothesis: There is a significant association between gender and job satisfaction.
Chi-square statistic: 4.429315025252526
P-value: 0.03532668256876494
Degrees of freedom: 1
Expected frequencies:
[[39.13043478 20.86956522]
 [35.86956522 19.13043478]]